In [2]:
# import de numpy
import numpy as np

In [18]:
M = np.random.rand(3,4) * 10
print(M)

[[9.98286082 3.8949701  8.65524424 0.81532538]
 [8.77193593 3.18651462 9.39342466 6.32465322]
 [2.946323   0.1195946  6.7785365  9.62396596]]


In [21]:
def rotation(M):
    return np.rot90(np.rot90(M))
M_rotated = rotation(M)
print(M_rotated)

[[9.62396596 6.7785365  0.1195946  2.946323  ]
 [6.32465322 9.39342466 3.18651462 8.77193593]
 [0.81532538 8.65524424 3.8949701  9.98286082]]


In [23]:
def multiply(M1, M2):
    s = 0
    for i in range(len(M1)):
        L1 = M1[i]
        L2 = M2[i]
        ss = 0
        for j in range(len(L1)):
            ss += L1[j] * L2[j]
        s += ss
    return s


In [52]:
M1 = np.random.randint(0,2, (4,5))
print(M1)
M1[:, 1:4]


[[1 0 0 0 0]
 [1 0 1 1 0]
 [1 0 0 0 1]
 [1 0 0 1 0]]


array([[0, 0, 0],
       [0, 1, 1],
       [0, 0, 0],
       [0, 0, 1]], dtype=int32)

In [53]:
def augmenter(M):
    x = M.shape
    M1 = np.zeros((x[0]+2,x[1]+2))
    M1[:, 1:-1][1:-1]=M
    return M1

print(augmenter(np.ones((2,2))))

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
