In [11]:
# Importer le numpy
import numpy as np

# Définir la matrice A
A = np.array([[4,6,-2,3], 
              [2,-1,0,1],
              [-7,0,1,12]])
A

array([[ 4,  6, -2,  3],
       [ 2, -1,  0,  1],
       [-7,  0,  1, 12]])

In [12]:
# Modifier la matrice les deux premières lignes A
A[:2] = A[:2] * 2
A

array([[ 8, 12, -4,  6],
       [ 4, -2,  0,  2],
       [-7,  0,  1, 12]])

In [13]:
# Modification de la dernière colonne
A[:, 3] = A[:, 3] / 3
A

array([[ 8, 12, -4,  2],
       [ 4, -2,  0,  0],
       [-7,  0,  1,  4]])

In [16]:
# Créer une nouvelle matrice ((4,5,6),(5,10,15), (1,1,1))
B = np.ones((3,3), dtype=int)
B

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
# Premiere ligne (4,5,6)
B[0] = np.arange(4,7)
B

array([[4, 5, 6],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
# Premiere ligne (5,10,15)
B[1] = np.arange(5,16,5)
B

array([[ 4,  5,  6],
       [ 5, 10, 15],
       [ 1,  1,  1]])

In [23]:
# d) Créer la matrice C € M(3,3) extraite de A telle que pour 1 <= i ; j <= 3, Cij = Aij
# C = A.copy()
C = np.zeros((3,3))
C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
[x**2 for x in range(1,20) if x % 2 == 0]

[4, 16, 36, 64, 100, 144, 196, 256, 324]

In [46]:
l= [[i,j] for i in range(len(C))  for j in range(len(A[0])) if i  >= 0 and j <3]

for x1,x2 in l:
    # print(type(x1),x2)
    C[x1,x2] = A[x1,x2]
C

array([[ 8., 12., -4.],
       [ 4., -2.,  0.],
       [-7.,  0.,  1.]])

In [52]:
# e-1) Réaliser le produit matriciel D 
D = np.dot(B,A)
# D_
print(D)
print()
print(B)
print()
print(A)

[[ 10  38 -10  32]
 [-25  40  -5  70]
 [  5  10  -3   6]]

[[ 4  5  6]
 [ 5 10 15]
 [ 1  1  1]]

[[ 8 12 -4  2]
 [ 4 -2  0  0]
 [-7  0  1  4]]


In [62]:
# e-2) Réaliser le produit matriciel d'Hadamard
H = np.ones((3,3), dtype=int)
for i in range(H.shape[0]):
    for j in range(H.shape[1]):
        H[i,j] = A[i,j] * B[i,j]
H

array([[ 32,  60, -24],
       [ 20, -20,   0],
       [ -7,   0,   1]])

In [61]:
A.shape

(3, 4)