In [3]:
import numpy as np

In [3]:
# A = np.array([[1,1,0], [0,1,1], [1,0,1]])

In [5]:
# A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 0, 1]])

In [6]:
# A.shape

In [5]:
# A[::,1]

In [7]:
#Exercice 1
## a) Définir la matrice A comme un np.array().

A = np.array([[4,6,-2,3], [2,-1,0,1], [-7,0,1,12]])
A

array([[ 4,  6, -2,  3],
       [ 2, -1,  0,  1],
       [-7,  0,  1, 12]])

In [26]:
# b) Modifier la matrice A pour que ses deux premières lignes soient mutlipliées par 2 et que sa dernière colonne soit divisée par 3.
A[:2] = A[:2]*2

A

array([[ 64,  96, -32,  48],
       [ 32, -16,   0,  16],
       [ -7,   0,   1,  12]])

In [65]:
# c) Créer une nouvelle matrice B définie par ((4,5,6),(5,10,15),(1,1,1))
B = np.ones((3,3), dtype=int)
# B


B[0] = np.arange(4,7)
B[1] = np.arange(5,16,5)
B


array([[ 4,  5,  6],
       [ 5, 10, 15],
       [ 1,  1,  1]])

In [63]:
# d) Créer la matrice C € M(3,3) extraite de A telle que pour 1 <= i,j <= 3, Cij = aij
C = A[::,:3]
C

array([[ 64,  96, -32],
       [ 32, -16,   0],
       [ -7,   0,   1]])

In [68]:
# e-1) Réaliser le produit matriciel D 
D = np.dot(B,A)
D


array([[ 374,  304, -122,  344],
       [ 535,  320, -145,  580],
       [  89,   80,  -31,   76]])

In [73]:
B

array([[ 4,  5,  6],
       [ 5, 10, 15],
       [ 1,  1,  1]])

In [ ]:
# e-2) Réaliser le produit d'HDAMARD E
E = 